apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-ui
  namespace: micromeetingschedular
  labels:
    app: react-ui
spec:
  selector:
    matchLabels:
      app: react-ui
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: react-ui
    spec:
      containers:
        - name: react-ui
          image: meetingScheduler/ui:latest
          ports:
            - containerPort: 8080
              name: react-ui
              resources:
                requests:
                  memory: "64Mi"
                  cpu: "250m"
                limits:
                  memory: "128Mi"
                  cpu: "500m"

---
apiVersion: v1
kind: Service
metadata:
  name: react-ui
  namespace: ms
spec:
  selector:
    app: react-ui
  type: NodePort
  ports:
    - name: react-ui
      port: 8080
      targetPort: 8080
