apiVersion: apps/v1
kind: Deployment
metadata:
  name: reactui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
        - name: user
          image: $CONTAINER_REGISTRY_LOGIN_SERVER/user:$VERSION
          imagePullPolicy: IfNotPresent
          env:
            - name: PORT
              value: "5001"
          resources:
            requests:
              cpu: 126m
              memory: 126Mi
            limits:
              cpu: 256m
              memory: 256Mi

---
apiVersion: v1
kind: Service
metadata:
  name: reactui
spec:
  selector:
    app: reactui
  type: NodePort
  ports:
    - name: reactui
      port: 8080
      targetPort: 8080
