apiVersion: v1
kind: Pod
metadata:
    name: user
    labels:
        app: user
spec:
    containers:
        - name: user
          image: $CONTAINER_REGISTRY_LOGIN_SERVER/user:$VERSION
          imagePullPolicy: IfNotPresent
          ports:
              - containerPort: 5001
          startupProbe:
              exec:
                  command:
                      - cat
                      - /tmp/started
              initialDelaySeconds: 5
              periodSeconds: 4
              failureThreshold: 10
          readinessProbe:
              tcpSocket:
                  port: 5001
              initialDelaySeconds: 5
              periodSeconds: 2
              failureThreshold: 10
          livenessProbe:
              httpGet:
                  path: /healthz
                  port: 5001
              initialDelaySeconds: 25
              periodSeconds: 2
              failureThreshold: 6
          resources:
              requests:
                  cpu: 100m
                  memory: 128Mi
              limits:
                  cpu: 250m
                  memory: 256Mi
