apiVersion: apps/v1
kind: Deployment
metadata:
    name: nginx-deployment
spec:
    selector:
        matchLabels:
            app: nginx
    replicas: 1
    template:
        metadata:
            labels:
                app: nginx
        spec:
            containers:
                - name: nginx
                  image: $CONTAINER_REGISTRY_LOGIN_SERVER/proxy:$VERSION
                  imagePullPolicy: IfNotPresent
                  ports:
                      - containerPort: 80
                  resources:
                      requests:
                          cpu: 200m
                          memory: 126Mi
                      limits:
                          cpu: 1000m
                          memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
    name: nginx
    labels:
        app: nginx
spec:
    ports:
        - name: nginx
          port: 80
          targetPort: 80
    selector:
        app: nginx
    type: LoadBalancer
